apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-wind
    url: postgres:5432
    user: admin
    secureJsonData:
      password: password
    jsonData:
      database: weather_db
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
